# Generated by Django 4.2.4 on 2024-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaff',
            name='trusted',
            field=models.BooleanField(default=False, verbose_name='Personal de confianza'),
        ),
        migrations.AddField(
            model_name='staff',
            name='trusted',
            field=models.BooleanField(default=False, verbose_name='Personal de confianza'),
        ),
    ]
