# Generated by Django 4.2.4 on 2024-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_historicalstaff_trusted_staff_trusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaff',
            name='hours_per_day',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Horas por día'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hours_per_day',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Horas por día'),
        ),
    ]
