# Generated by Django 4.2.4 on 2024-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_historicalstaff_hours_per_day_staff_hours_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaff',
            name='hours_saturday',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Horas por sábado'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='hours_sunday',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Horas por domingo'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hours_saturday',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Horas por sábado'),
        ),
        migrations.AddField(
            model_name='staff',
            name='hours_sunday',
            field=models.TimeField(blank=True, default='08:00:00', null=True, verbose_name='Horas por domingo'),
        ),
    ]
