// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// STAFF
export const GET_STAFFS_SUCCESS = 'GET_STAFFS_SUCCESS';
export const GET_STAFFS_FAIL = 'GET_STAFFS_FAIL';
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS';
export const GET_DEPARTMENTS_FAIL = 'GET_DEPARTMENTS_FAIL';
export const GET_ABSENTEEISM_SUCCESS = 'GET_ABSENTEEISM_SUCCESS';
export const GET_ABSENTEEISM_FAIL = 'GET_ABSENTEEISM_FAIL';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAIL = 'ADD_STAFF_FAIL';
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS';
export const UPDATE_STAFF_FAIL = 'UPDATE_STAFF_FAIL';
export const GET_USERS_NOT_TRACKING_SUCCESS = 'GET_USERS_NOT_TRACKING_SUCCESS';
export const GET_USERS_NOT_TRACKING_FAIL = 'GET_USERS_NOT_TRACKING_FAIL';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const FIND_USER_FAIL = 'FIND_USER_FAIL';

// TRACKING
export const GET_TRACKING_SUCCESS = 'GET_TRACKING_SUCCESS';
export const GET_TRACKING_FAIL = 'GET_TRACKING_FAIL';

export const GET_REAL_TRACKING_SUCCESS = 'GET_REAL_TRACKING_SUCCESS';
export const GET_REAL_TRACKING_FAIL = 'GET_REAL_TRACKING_FAIL';

export const ADD_TRACKING_SUCCESS = 'ADD_TRACKING_SUCCESS';
export const ADD_TRACKING_FAIL = 'ADD_TRACKING_FAIL';

export const UPDATE_TRACKING_SUCCESS = 'UPDATE_TRACKING_SUCCESS';
export const UPDATE_TRACKING_FAIL = 'UPDATE_TRACKING_FAIL';

export const SEND_TRACKING_SUCCESS = 'SEND_TRACKING_SUCCESS';
export const SEND_TRACKING_FAIL = 'SEND_TRACKING_FAIL';

export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS';
export const GET_SUMMARY_FAIL = 'GET_SUMMARY_FAIL';

export const GET_OUTSOURCING_SUCCESS = 'GET_OUTSOURCING_SUCCESS';
export const GET_OUTSOURCING_FAIL = 'GET_OUTSOURCING_FAIL';

export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_FAIL = 'GET_CALENDAR_FAIL';

export const GET_OVERTIME_SUCCESS = 'GET_OVERTIME_SUCCESS';
export const GET_OVERTIME_FAIL = 'GET_OVERTIME_FAIL';

export const SYNC_OVERTIME_SUCCESS = 'SYNC_OVERTIME_SUCCESS';
export const SYNC_OVERTIME_FAIL = 'SYNC_OVERTIME_FAIL';


/*AUTHENTICATION*/

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';