# Generated by Django 4.2.4 on 2024-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='permissions',
            field=models.CharField(choices=[('EDITOR', 'Editor'), ('VIEWER', 'Visualizador'), ('FIND', 'Buscador')], default='EDITOR', max_length=10, verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='permissions',
            field=models.CharField(choices=[('EDITOR', 'Editor'), ('VIEWER', 'Visualizador'), ('FIND', 'Buscador')], default='EDITOR', max_length=10, verbose_name='Permisos'),
        ),
    ]
