# Generated by Django 4.2.4 on 2024-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='delay_hours',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Horas de retraso'),
        ),
    ]
